// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iineewmmosoieamczxga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlpbmVld21tb3NvaWVhbWN6eGdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NDc5NTQsImV4cCI6MjA3MDUyMzk1NH0.e8ymZm7hbRIUAq0i2cNgOE-JdKBqVifW64S8Avxjqs0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});